server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: abn
    password: password
    mvc:
      pathmatch:
        matching-strategy: ANT_PATH_MATCHER
  jpa:
    open-in-view: false
    properties:
      hibernate:
        search:
          backend:
            type: lucene
            directory.root: ./data/index